// VOSS AUTOGENERATED FILE, DO NOT MODIFY.

import { Builder, EnumCase, Reader, Struct } from './runtime';
import { IBuilder } from './runtime/builder';
type UUID = string;

export class Test2 implements Struct {
  readonly _maxElementAlignment = 4;
  readonly _size = 4;
  constructor(readonly $session: VossSession, private __t: number) {}

  get t() {
    return this.__t;
  }

  _serialize(builder: Builder) {
    builder.u32(0, this.__t);
  }

  static deserialize(session: VossSession, reader: Reader) {
    return new Test2(session, reader.u32(0));
  }
}

export class Test implements Struct {
  readonly _maxElementAlignment = 4;
  readonly _size = 12;
  constructor(
    readonly $session: VossSession,
    private __value: number,
    private __v: boolean,
    private __data: Test2
  ) {}

  get value() {
    return this.__value;
  }

  get v() {
    return this.__v;
  }

  get data() {
    return this.__data;
  }

  _serialize(builder: Builder) {
    builder.i32(0, this.__value);
    builder.bool(4, this.__v);
    builder.struct(8, this.__data);
  }
}

export class _ClockData implements Struct {
  readonly _maxElementAlignment = 8;
  readonly _size = 8;
  constructor(readonly $session: VossSession, private __timestamp: number) {}

  get timestamp() {
    return this.__timestamp;
  }

  _serialize(builder: Builder) {
    builder.f64(0, this.__timestamp);
  }

  static deserialize(session: VossSession, reader: Reader) {
    return new _ClockData(session, reader.f64(0));
  }
}

class VossSession {}
